<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>

		<RootNamespace>BATools_Installer</RootNamespace>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishSingleFile>true</PublishSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<Configurations>Debug;Release R25;Release R26;Debug R26</Configurations>
	</PropertyGroup>

	<ItemGroup>
	  <Reference Include="RevitAPI">
	    <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Revit 2025\RevitAPI.dll</HintPath>
	  </Reference>
	  <Reference Include="RevitAPIUI">
	    <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Revit 2025\RevitAPIUI.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
