//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tooltips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BA.Resources.Files.Tooltips", typeof(Tooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *SHIFT + RightCLick ---&gt; Settings*
        ///Place room axis into selected rooms.
        ///Select RoomTags.
        /// </summary>
        internal static string AxisToRoom {
            get {
                return ResourceManager.GetString("AxisToRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use for linked rooms.
        /// </summary>
        internal static string AxisToRoom_Link {
            get {
                return ResourceManager.GetString("AxisToRoom_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use for rooms created in session.
        /// </summary>
        internal static string AxisToRoom_Local {
            get {
                return ResourceManager.GetString("AxisToRoom_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watches for changes since &quot;Start&quot; is pressed until &quot;Stop&quot;.
        /// </summary>
        internal static string ChangeMonitor {
            get {
                return ResourceManager.GetString("ChangeMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string EditDimension {
            get {
                return ResourceManager.GetString("EditDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show elements above cut plane.
        /// </summary>
        internal static string OverheadCommand_OverheadCommand {
            get {
                return ResourceManager.GetString("OverheadCommand_OverheadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a pulldown button.
        /// </summary>
        internal static string PullDown {
            get {
                return ResourceManager.GetString("PullDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button 1.
        /// </summary>
        internal static string PullDown_1Button {
            get {
                return ResourceManager.GetString("PullDown_1Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button 2.
        /// </summary>
        internal static string PullDown_2Button {
            get {
                return ResourceManager.GetString("PullDown_2Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button 3.
        /// </summary>
        internal static string PullDown_3Button {
            get {
                return ResourceManager.GetString("PullDown_3Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex.
        /// </summary>
        internal static string Stack1 {
            get {
                return ResourceManager.GetString("Stack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex B.
        /// </summary>
        internal static string Stack1_Button {
            get {
                return ResourceManager.GetString("Stack1_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex.
        /// </summary>
        internal static string Stack2 {
            get {
                return ResourceManager.GetString("Stack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex B.
        /// </summary>
        internal static string Stack2_Button {
            get {
                return ResourceManager.GetString("Stack2_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex.
        /// </summary>
        internal static string Stack3 {
            get {
                return ResourceManager.GetString("Stack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex B.
        /// </summary>
        internal static string Stack3_Button {
            get {
                return ResourceManager.GetString("Stack3_Button", resourceCulture);
            }
        }
    }
}
