<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <Configurations>  Debug R24;Debug R25;Debug R26</Configurations>
        <Configurations>$(Configurations);Release R24;Release R25;Release R26</Configurations>
		<RootNamespace>BA.UI</RootNamespace>
    </PropertyGroup>

    <!-- Revit configuration -->

    <PropertyGroup Condition="$(Configuration.Contains('R24'))">
        <RevitVersion>2024</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R25'))">
        <RevitVersion>2025</RevitVersion>
        <TargetFramework>net8.0-windows</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R26'))">
        <RevitVersion>2026</RevitVersion>
        <TargetFramework>net8.0-windows</TargetFramework>
    </PropertyGroup>

    <!-- Launch configuration -->
    <PropertyGroup>
        <StartAction>Program</StartAction>
        <StartProgram>C:\Program Files\Autodesk\Revit $(RevitVersion)\Revit.exe</StartProgram>
        <StartArguments>/language ENG</StartArguments>
    </PropertyGroup>

    <!-- Build configuration -->
    <!-- https://github.com/Nice3point/Revit.Build.Tasks -->
    <PropertyGroup>
        <IsRepackable>false</IsRepackable>
        <DeployRevitAddin>true</DeployRevitAddin>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove="Keyplan\New\**" />
      <Compile Remove="Keyplan\Update\**" />
      <Compile Remove="Keyplan\Utils§\**" />
      <EmbeddedResource Remove="Keyplan\New\**" />
      <EmbeddedResource Remove="Keyplan\Update\**" />
      <EmbeddedResource Remove="Keyplan\Utils§\**" />
      <None Remove="Keyplan\New\**" />
      <None Remove="Keyplan\Update\**" />
      <None Remove="Keyplan\Utils§\**" />
      <Page Remove="Keyplan\New\**" />
      <Page Remove="Keyplan\Update\**" />
      <Page Remove="Keyplan\Utils§\**" />
    </ItemGroup>
    <ItemGroup>
      <Compile Remove="Commands\Anno\Cmd_GenerateKeyplanDraftingView .cs" />
      <Compile Remove="Commands\Anno\Cmd_UpdateKeyplansOnSheets.CS" />
    </ItemGroup>
    <ItemGroup>
      <None Remove="Resources\Icons16\ArAnnoStt_16.png" />
      <None Remove="Resources\Icons16\ArAnnoSt_16.png" />
      <None Remove="Resources\Icons16\ArAnno_16.png" />
      <None Remove="Resources\Icons16\ause16.png" />
      <None Remove="Resources\Icons16\AxisToRoom16.png" />
      <None Remove="Resources\Icons16\AxistoRoom_Link16.png" />
      <None Remove="Resources\Icons16\AxistoRoom_Local16.png" />
      <None Remove="Resources\Icons16\brws_16.png" />
      <None Remove="Resources\Icons16\ChangeMonitor16.png" />
      <None Remove="Resources\Icons16\Classif16.png" />
      <None Remove="Resources\Icons16\Cleanup_Cleanup16.png" />
      <None Remove="Resources\Icons16\DimOveride_OverrideDimension16.png" />
      <None Remove="Resources\Icons16\DimOveride_OverrideDimensionSegment16.png" />
      <None Remove="Resources\Icons16\DimOverride16.png" />
      <None Remove="Resources\Icons16\ElementToRoom16.png" />
      <None Remove="Resources\Icons16\FIN16.png" />
      <None Remove="Resources\Icons16\General_Test16.png" />
      <None Remove="Resources\Icons16\lib_16.png" />
      <None Remove="Resources\Icons16\Menu_16.png" />
      <None Remove="Resources\Icons16\OverheadCommand_OverheadCommand166.png" />
      <None Remove="Resources\Icons16\Temp16.png" />
      <None Remove="Resources\Icons16\TRA_16.png" />
      <None Remove="Resources\Icons16\txt16.png" />
      <None Remove="Resources\Icons16\use16.png" />
      <None Remove="Resources\Icons16\ZoomtoRoom16.png" />
      <None Remove="Resources\Icons32\ArAnnoStt_32.png" />
      <None Remove="Resources\Icons32\ArAnnoSt_32.bak.png" />
      <None Remove="Resources\Icons32\ArAnnoSt_32.png" />
      <None Remove="Resources\Icons32\ArAnno_32.png" />
      <None Remove="Resources\Icons32\ause32.png" />
      <None Remove="Resources\Icons32\AxisToRoom32.png" />
      <None Remove="Resources\Icons32\brws_32.png" />
      <None Remove="Resources\Icons32\ChangeMonitor32.png" />
      <None Remove="Resources\Icons32\Classif32.png" />
      <None Remove="Resources\Icons32\Cleanup_Cleanup16.png" />
      <None Remove="Resources\Icons32\Cleanup_Cleanup32.png" />
      <None Remove="Resources\Icons32\DimOveride_OverrideDimension32.png" />
      <None Remove="Resources\Icons32\DimOveride_OverrideDimensionSegment32.png" />
      <None Remove="Resources\Icons32\DimOverride32.png" />
      <None Remove="Resources\Icons32\ElementToRoom32.png" />
      <None Remove="Resources\Icons32\FIN32.png" />
      <None Remove="Resources\Icons32\General_Test32.png" />
      <None Remove="Resources\Icons32\lib_32.png" />
      <None Remove="Resources\Icons32\Menu_32.png" />
      <None Remove="Resources\Icons32\Temp32.png" />
      <None Remove="Resources\Icons32\TRA_32.png" />
      <None Remove="Resources\Icons32\use32.png" />
      <None Remove="Resources\Icons32\ZoomtoRoom32.png" />
    </ItemGroup>

    <ItemGroup>
        <!-- Revit References -->
        <PackageReference Include="ClosedXML" Version="0.105.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Nice3point.Revit.Build.Tasks" Version="3.0.1" />
        <PackageReference Include="Nice3point.Revit.Toolkit" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Extensions" Version="2026.0.2-preview.1.20251113" />
        <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*" />

        <!-- MVVM -->
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    </ItemGroup>
    
    <ItemGroup>
        <Resource Include="Resources\Icons16\ArAnno_16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\ause16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\AxisToRoom16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\AxistoRoom_Link16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\AxistoRoom_Local16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\brws_16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\ChangeMonitor16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\Classif16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\Cleanup_Cleanup16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\DimOveride_OverrideDimension16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\DimOveride_OverrideDimensionSegment16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\DimOverride16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\ElementToRoom16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\ElementToRoom_link16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\ElementToRoom_local16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\FamilyParameters16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\FIN16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\General_Test16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\lib_16.png" />
        <Resource Include="Resources\Icons16\Menu_16.png" />
        <Resource Include="Resources\Icons16\OverheadCommand16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\OverheadCommand_OverheadCommand166.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\RayBounceCeiling16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\SheetDateAndRevision16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\Temp16.png" />
        <Resource Include="Resources\Icons16\TRA_16.png" />
        <Resource Include="Resources\Icons16\txt16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\use16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons16\ZoomtoRoom16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\ArAnnoStt_32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\ArAnnoSt_32.bak.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\ArAnnoSt_32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\ArAnno_32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\ause32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\AxisToRoom32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\AxisToRoo_Link32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\AxisToRoom_Link32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\AxisToRoom_Local32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\AxisToRoo_Local32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\brws_32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\ChangeMonitor32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\Classif32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\Cleanup_Cleanup16.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\Cleanup_Cleanup32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\DimOveride_OverrideDimension32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\DimOveride_OverrideDimensionSegment32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\DimOverride32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\ElementToRoom32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\ElementToRoom_link32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\ElementToRoom_local32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\FamilyParameters32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\FIN32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\General_Test32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\lib_32.png" />
        <Resource Include="Resources\Icons32\Menu_32.png" />
        <Resource Include="Resources\Icons32\OverheadCommand32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\RayBounceCeiling32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\SheetDateAndRevision32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\Temp32.png" />
        <Resource Include="Resources\Icons32\TRA_32.png" />
        <Resource Include="Resources\Icons32\use32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons32\ZoomtoRoom32.png">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Resources\Icons\RibbonIcon16.png" />
        <Resource Include="Resources\Icons\RibbonIcon32.png" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Models" />
        <Folder Include="NewFolder\" />
        <Folder Include="ViewModels\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Ribbon\RibbonExtensions.cs">
        <Generator>MSBuild:Compile</Generator>
      </Compile>
    </ItemGroup>
	

</Project>